<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="NSL-MFERNANDEZs-MacBook-Pro.local" name="Tests.ikonEpicTest" tests="9" failures="0" timestamp="15 Apr 2019 17:43:08 GMT" time="19.490" errors="1">
  <testcase name="ikonPage" time="0.817" classname="Tests.ikonEpicTest"/>
  <testcase name="ikonPasses" time="0.615" classname="Tests.ikonEpicTest"/>
  <testcase name="ikonAdultPasses" time="0.277" classname="Tests.ikonEpicTest">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
at Pages.epic.AddAdultPass(epic.java:100)
at Tests.ikonEpicTest.ikonAdultPasses(ikonEpicTest.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- ikonAdultPasses -->
  <testcase name="ikonChildPasses" time="0.077" classname="Tests.ikonEpicTest"/>
  <testcase name="removeikonChildPasses" time="0.101" classname="Tests.ikonEpicTest"/>
  <testcase name="ikonEpicPasses" time="5.240" classname="Tests.ikonEpicTest"/>
  <testcase name="clickLetBook" time="4.152" classname="Tests.ikonEpicTest"/>
  <testcase name="setTravelers" time="6.601" classname="Tests.ikonEpicTest"/>
  <testcase name="BillingInformation" time="1.610" classname="Tests.ikonEpicTest"/>
</testsuite> <!-- Tests.ikonEpicTest -->
